name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - pdf

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: change language
        run: |
          sudo apt-get install -y fonts-noto-cjk
          export LANG=zh_CN.UTF-8
          export LANGUAGE=zh_CN:zh
          export LC_ALL=zh_CN.UTF-8

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-with-pdf mkdocs-glightbox

      - name: Build Docs
        run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site